---
driver:
  name: docker
  use_sudo: false
  privileged: true

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: all
  enable_yum_epel: true
  idempotency_test: true
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
    image: centos:7
    privileged: true
    run_command: /usr/sbin/init

suites:
- name: default
