---

- name: New Relic sysmond | Setup yum repo
  yum: name=https://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm state=present

- name: New Relic sysmond | Install newrelic-sysmond
  yum: name=newrelic-sysmond state=present
